derat/ascenso

src/components/ClimbDropdown.vue, src/components/ClimbState.js, src/components/Climbs.vue
create a second dropdown next to the first one, for the second climber
=> move "climb state dropdown" to its own component

src/components/ClimbDropdown.vue, src/components/Routes.vue, src/components/Scoreboard.vue, src/components/Statistics.vue, src/main.js
- rename Climbs.vue to Routes.vue
- make component styles scoped
- remove extra blank lines
=> misc cleanup

.gitignore, package-lock.json, package.json, src/App.vue, src/components/Login.vue, src/main.js
This uses FirebaseUI to add a spartan login page with Google
and email authentication, and requires auth to view any
other pages. It also adds a "Sign Out" item to the
navigation drawer.
Run "npm install" to install the new firebase and firebaseui
dependencies. A new (not checked in) src/firebase.js file
containing configuration info is also needed.
Further reading:
https://medium.com/@anas.mammeri/vue-2-firebase-how-to-build-a-vue-app-with-firebase-authentication-system-in-15-minutes-fdce6f289c3c
https://medium.com/js-dojo/vue-authentication-with-firebase-ui-3610ef7f89ee
https://medium.com/dailyjs/authenticating-a-vue-js-application-with-firebase-ui-8870a3a5cff8
=> Add basic FirebaseUI auth support.

.gitignore, README.md, package-lock.json, package.json, src/App.vue, src/components/Toolbar.vue, src/firebase/index.js, src/main.js, src/router/index.js, src/views/Login.vue
Make the string in the titlebar get updated from a new
globals/config document in Cloud Firestore. Also heavily
refactor the way that Firebase is initialized, and move
src/firebase.js to src/firebase/config.js.
Unrelatedly, unset the 'no-console' ESLint check to permit
using console.log for debugging.
=> Add trivial Cloud Firestore binding.

README.md, src/App.vue, src/components/RouteList.vue, src/main.js, src/views/Routes.vue
Update the Routes and RouteList components to query a new
global/sortedData document in Cloud Firestore. This document
was created by a not-yet-committed Cloud Function and
contains sorted information about areas and routes.
=> Update Routes and RouteList to use new schema.

src/firebase/index.js
Configure Firestore to permit reads and writes while
offline.
=> Enable Firestore persistence.

src/components/Spinner.vue, src/views/Routes.vue, src/views/Statistics.vue
Update the Statistics view to compute and display points and
climbs. Also create a new Spinner component for displaying a
fullscreen indeterminate-progress indicator.
=> Display basic statistics.

README.md, src/components/Toolbar.vue, src/views/Profile.vue
Update the Profile view to contain UI for creating, joining,
and leaving a team. None of this is wired up to Firestore
yet.
Also update the Toolbar view to use the theme's primary
color instead of "blue".
=> Start adding team UI to profile view.

README.md, firestore.rules, src/views/Profile.vue
Update the Profile view's team-related UI to use the
Firestore backend.
=> Wire up profile view team UI to Firestore.

.prettierrc, babel.config.js, firebase.json, public/index.html, src/App.vue, src/components/ClimbDropdown.vue, src/components/ClimbState.js, src/components/RouteList.vue, src/components/Spinner.vue, src/components/StatisticsList.vue, src/components/StatisticsRow.vue, src/components/Toolbar.vue, src/plugins/vuetify.js, src/views/Login.vue, src/views/Profile.vue, src/views/Routes.vue, src/views/Scoreboard.vue, src/views/Statistics.vue, vue.config.js
Use prettier to format all .js, .json, .html, and .vue
files. Also add a .prettierrc file with desired settings.
=> Format all files.

src/views/Profile.vue
Remove nesting in promise chains and add a bunch of
comments.
=> Make JS in profile view less terrible.

README.md, src/App.vue, src/components/ClimbDropdown.vue, src/components/RouteList.vue, src/views/Profile.vue, src/views/Routes.vue
Store climbs in the team document when the user is on a
team, and update the Routes view to create a ClimbDropdown
component for each climber on the team.
=> Track climbs for each team member.

src/components/Toolbar.vue, src/plugins/vuetify.js, src/views/Profile.vue
Pass several custom colors when initializing Vuetify, and
also use "color" attributes more consistently in the Profile
view.
=> Set theme colors and rework styling in profile view.

src/components/ClimbDropdown.vue, src/components/RouteList.vue, src/views/Routes.vue
Update the Routes view to pass an array to the RouteList
component that controls the colors used by the ClimbDropdown
component. More work is still needed to make it clear which
climber is represented by each column.
=> Assign a different color to each climber.

src/components/Toolbar.vue
Update the <v-toolbar> in the Toolbar component to scroll
offscreen when the user scrolls down and scroll back
onscreen when the user scrolls up.
=> Make toolbar scroll offscreen.

src/climbs/index.js, src/components/ClimbDropdown.vue, src/components/ClimbState.js, src/components/RouteList.vue, src/views/Routes.vue, src/views/Statistics.vue
Add a new climbs/index.js file that defines a ClimberInfo
class that stores climber-related information. This is
passed through from the Routes view to the ClimbDropdown
component and contains a map from route ID to ClimbState, a
color, and the climber's name.
Also move the ClimbState enum into this file.
=> Add ClimberInfo class.

src/components/ClimbDropdown.vue, src/components/RouteList.vue, src/components/Toolbar.vue, src/firebase/index.ts, src/main.ts, src/models.ts, src/views/Login.vue, src/views/Profile.vue, src/views/Routes.vue, src/views/Scoreboard.vue, src/views/Statistics.vue
Update all views to use TypeScript instead of JavaScript.
Also add more exports to models.ts and make some static
component data be readonly members.
=> Convert views to TypeScript.

src/components/StatisticsList.vue, src/components/StatisticsRow.vue, src/views/Statistics.vue
Update the Statistics view to display tabs for viewing team
and individual stats, and group stats into multiple cards.
Also delete old unused styles and get rid of ugly padding in
StatisticsList component.
=> Add tabs to statistics view and add grouping.

INSTALL.md, README.md
Move installation instructions from README.md to a new
INSTALL.md file and expand them.
=> Improve installation instructions.

INSTALL.md, README.md, firebase.json, src/views/Login.vue, storage.rules
Update the Login view to display a 400x400 competition logo,
and place the login buttons inside a card.
Also update instructions for setting up Cloud Storage and
add a storage.rules file that allows unauthenticated access
to a "public" directory in the default bucket.
=> Include competition logo in login view.

admin/admin.go, admin/firestore.go, admin/routes.go, admin/scores.go, admin/scores_test.go, go.mod
Add a new button to the page served by the "Admin" Cloud
Function that generates a page listing teams' scores. Also
move Firestore-related constants and types to a separate
firestore.go file.
=> Add support for viewing scores on admin page.

INSTALL.md, ascenso.go, go.mod, go.sum, log/log.go
Add a new "Log" Cloud Function that accepts an array of log
entries over HTTPS and records them using Stackdriver.
=> Add "Log" Cloud Function.

package-lock.json, package.json, src/main.ts, src/plugins/i18n.ts, src/plugins/vuetify.ts, src/views/Profile.vue
=> add vue-i18n package, and show example usage via 3 strings in user

.travis.yml, README.md
Add a config file for Travis CI to run JS and Go unit tests.
=> Add .travis.yml.

src/App.vue, src/firebase/index.ts, src/firebase/logger.ts, src/main.ts, src/mixins/Perf.ts, src/views/Login.vue
Remove the 'load_app' log entry reported by main.ts, and
instead update the App view to report 'app_loaded' timing
info that includes the user agent.
Also make the Login view report timing info.
=> Improve app-level perf reporting.

src/firebase/index.ts, src/firebase/init.ts, src/firebase/mock.ts, src/main.ts, src/views/Statistics.test.ts, src/views/Statistics.vue
Add rudimentary support for mocking Firebase and use it to
write a test for the Statistics view.
(I couldn't get any of the existing unofficial Firebase test
libraries to work, so I wrote my own terrible one. There is
no official test library.)
=> Add test for Statistics view.

src/firebase/mock.ts, src/models.ts, src/views/Routes.test.ts, src/views/Statistics.test.ts
Also update Firebase mocking code to support vuefire's
$unbind() and DocumentReference.update().
=> Add unit tests for Routes view.

package-lock.json, package.json, src/firebase/index.ts, src/firebase/mock.ts, src/testutil.ts, src/views/Profile.test.ts, src/views/Profile.vue
This covers editing user and team names, viewing team
members, showing invite codes, and leaving teams.
=> Start adding unit tests for Profile view.

src/firebase/index.ts, src/firebase/mock.ts, src/views/Profile.test.ts, src/views/Profile.vue
Test creating and joining teams. Also make logError suppress
console logging in test mode since it spams output when
tests are exercising error paths.
=> Add more unit tests for Profile view.

src/App.vue, src/views/Profile.vue, src/views/Routes.vue, src/views/Statistics.vue
Add a v-snackbar component to the main App view that
displays transient messages to users when components emit
success-msg, error-msg, or info-msg events.
=> Add support for displaying errors and other messages.

src/views/Profile.test.ts, src/views/Profile.vue
Clean up user and team names before applying them, and wrap
many operations in promises to make it easier to share
error-handling code.
=> Resolve various TODOs in Profile view.

INSTALL.md
Add hyperlinks to a few local files mentioned in INSTALL.md
and suggest using 302 redirects rather than 301 (since it's
hard/impossible to make changes after adding a 301).
=> Minor tweaks to INSTALL.md.

src/main.ts, src/router/index.test.ts
Add unit tests for the VueRouter instance. Also disable Vue
devtools spam in main.ts.
=> Add router unit tests.

go/admin/admin.go, go/admin/clear_scores.go, go/admin/empty_teams.go, go/admin/routes.go, go/admin/routes_test.go, go/admin/scores.go, go/admin/scores_test.go, go/db/firestore.go
Move the admin/firestore.go file into a new "db" package
so it can be shared with other Cloud Functions.
=> Create "db" Go package.

ascenso.go, go.mod, go/admin/empty_teams.go, go/db/firestore.go, go/test/func.go
Add a new Cloud Function that can be used by end-to-end
tests. It currently only supports deleting test users.
=> Add "Test" Cloud Function.

go/admin/empty_teams.go
Update the "Delete empty teams" feature so it deletes the
invite docs associated with teams that are being deleted.
=> Make "Admin" Cloud Function delete invites with empty teams.

src/components/Toolbar.test.ts, src/components/Toolbar.vue, src/views/Profile.test.ts, src/views/Profile.vue
Add id attributes to various elements so they can be
accessed in end-to-end tests. Also make ref attribute naming
more consistent.
=> Add IDs to elements in Toolbar and Profile components.

.env.example, deploy_all.sh, deploy_cloud_function.sh
Add a script that builds and deploys the site, along with
deploying Firestore rules and Cloud Functions. Also make a
few minor improvements to comments.
=> Add deploy_all.sh script.

e2e/globals.ts, e2e/pages/README.md, e2e/pages/login.ts, e2e/pages/profile.ts, e2e/pages/routes.ts, e2e/pages/toolbar.ts, e2e/tests/test.ts, nightwatch.conf.js, src/components/ClimbDropdown.vue, src/components/RouteList.vue, src/components/Toolbar.vue, src/views/Login.vue, src/views/Routes.vue
Define Nightwatch Page Objects to move some logic out of the
main test flow. Also exercise setting a climb's state and
logging out.
=> Refactor end-to-end tests to use Page Objects.

src/App.vue, src/router/routes.ts, src/views/Print.test.ts, src/views/Print.vue, src/views/Routes.vue
Add a new "Print" view (accessible at /print) that displays
a scorecard formatted for printing in landscape mode.
=> Add printable scorecard.

src/App.vue, src/components/Toolbar.vue, src/router/routes.ts
Update the Toolbar component to display the current view's
title (e.g. "Routes", "Profile", etc.). Also use the default
slot to insert a new route-supplied "nav" component into the
toolbar.
=> Display view name in toolbar.

src/components/Toolbar.vue, src/views/Profile.vue
Add dividers between dialog text and buttons, which makes
the differing margin sizes look less strange.
Also add "Cancel" buttons to all dialogs and make button
colors more uniform.
=> Make dialogs look less crappy.

src/views/Profile.vue
Remove unnecessary v-row and v-col elements that added extra
space around the name inputs and roster in the Profile view.
=> Remove excessive spacing in Profile cards.

src/views/Routes.test.ts, src/views/Routes.vue
Update the Routes view to display the number of available
(i.e. not filtered out and not yet climbed) routes at the
right side of each area's expansion panel header.
=> Display counts of available climbs in Routes view.

package-lock.json, package.json, src/components/RouteList.vue
Upgrade the vuetify package from 2.0.17 to 2.1.9, the latest
release. Also upgrade eslint-plugin-vuetify to 1.0.0-beta.5
and vuetify-loader to 1.3.0.
Also move a padding class from one element to another in the
RouteList component since the climb dropdown buttons appear
to be squished together after the upgrade.
=> Update Vuetify to 2.1.9.

package-lock.json, package.json
Update packages to fix probably-unimportant vulnerabilities
reported by "npm audit" in the handlebars, braces, and
https-proxy-agent packages.
=> Fix vulnerabilities reported by "npm audit".

package-lock.json, package.json
Update the firebase package from 6.3.0 to 6.6.2. This also
pulls in newer versions of various dependencies.
=> Update firebase package to 6.6.2.

package-lock.json, package.json
Upgrade the vuetify package from 2.2.4 to 2.2.8. I've only
seen minor bugfixes in the release notes.
=> Upgrade Vuetify to 2.2.8.

package-lock.json
For some reason package-lock.json gets updated again when I
run 'npm install'.
=> Check in automated changes to package-lock.json.

src/components/RouteList.vue, src/views/Routes.vue
I think that something changed in Vuetify such that linked
icons end up underlined.
=> Get rid of blue underlines on Mountain Project links.

src/views/Statistics.vue
This is hopefully an improvement for the case where someone
climbs 80+ routes. They'll probably be amused to see all the
routes listed in a miniscule font, at least.
=> Make stats image 1080x1350 and scale font size.

src/views/Routes.test.ts, src/views/Routes.vue
Only include the seconds until the competition start or end
when it's less than a minute away. Otherwise, the line wraps
on phones.
=> Shorten long time strings in Routes view.
