src/router/index.js

Use history mode when instantiating the VueRouter object so
that the different views use paths like "/stats" instead of
ugly fragments like "/#/stats". History mode uses the HTML5
History API to manipulate URLs.
Firebase Hosting is already configured to rewrite all paths
to /index.html to handle users loading alternate paths
directly.

Update Vue Router to use history mode.

---

README.md
src/components/RouteList.vue
src/views/Routes.vue

Get areas from a new "areas" collection in Cloud Firestore,
and introduce a new RouteList component that gets routes
from a "routes" subcollection within each area.

Get route data from Cloud Firestore.

---

src/components/ClimbDropdown.vue
src/components/RouteList.vue
src/views/Routes.vue

Add the 'lazy' attribute to <v-menu> in the ClimbDropdown
component. This reduces initial RouteList render time from
7.5-8s to 4.5-5s when displaying four ClimbDropdowns per
route on my laptop.
Also use frozen objects to store constant information about
states so that Vue doesn't need to watch for changes.

Lazily render menus in ClimbDropdown.

---

firebase.json
package-lock.json
package.json
src/router/index.js
vue.config.js

Make vue-router only load the Login view when it's needed.
This reduces the chunk-vendors size by 200+ KB, since it
lets us lazily import firebaseui.
Unfortunately, the firebase package itself is still huge
(592 KB minified, 154 KB gzipped), and we need it in order
to do much of anything.
Also add vue-cli-plugin-webpack-bundle-analyzer, which
generates a report.html file in the dist directory showing
the sizes of different modules.
Update firebase.json to exclude report.html and remove some
default excludes that don't make sense to me (since they're
referencing things that aren't in the dist dir).

Lazily load login view.

---

src/components/StatisticsList.vue
src/components/StatisticsRow.vue
src/views/Statistics.vue

Introduce new StatisticsList and StatisticsRow components
that allow recursively nesting lists in the Statistics view.
Use nesting for lead and top-rope climb counts, and add a
new "Areas climbed" stat.

Support sub-lists in Statistics view.

---

src/views/Routes.vue

The area headings in the Routes view were just using the
default (small) font size. Set them to 16px to match the
size used for route names.

Increase font size for area names in Routes view.

---

src/views/Profile.vue

This was only used for a single _.isEmpty() call but
increased the uncompressed chunk-vendors JS size by 71 KB.

Remove lodash from profile view.

---

src/views/Profile.vue
src/views/Routes.vue

Explicitly reset Firebase snapshot properties to empty
objects when unbinding them in the Profile and Routes views.
vue-firebase seems to (sometimes?) set them to null even
when asked to do otherwise.

Explicitly reset doc snapshots when unbinding.

---

firestore.rules
public/index.html
src/components/Toolbar.vue
src/main.js

Make the page use the competition name as its title.
"Loading..." is used as the initial title.
Also permit unauthenticated access to the global/config
document, and add a loggedIn() function to firestore.rules
to reduce repetition and avoid (harmless?) null dereferences
of request.auth.

Use competition name as page title.

---

src/views/Routes.vue

Change the first climber's color from orange to red. The
lighter shade of orange was a bit too light, and red and
indigo should still be distinguishable with the three most
common types of color-blindness, per a page I looked at.

Change first climber's color to red.

---

src/users/index.js
src/views/Profile.vue
src/views/Statistics.vue

- separate the loading of user and team climbs from database into a
helper function
TESTED:went to stats page when not on a team, when on a team of 1, and
when on a team of 2, added and removed climbs

- use both user and team climb data to populate stats page

---

src/components/Toolbar.vue
src/views/Profile.vue
src/views/Routes.vue
src/views/Statistics.vue
tsconfig.json

Set the noUnusedLocals option in tsconfig.json to force
compilation errors for unused variables. Also remove unused
variables that had crept in since the move to TypeScript.

Disallow unused variables.

---

src/components/ClimbDropdown.vue
src/components/RouteList.vue
src/models.ts

When a route hasn't been climbed yet, make ClimbDropdown's
button include the climber's initials.

Add climbers' initials to drop-down menus.

---

src/components/RouteList.vue
src/components/Toolbar.vue
src/views/Profile.vue
src/views/Routes.vue
src/views/Statistics.vue

Use the ":foo" shorthand instead of the lengthier
"v-bind:foo" syntax in components.

Get rid of unnecessary v-bind: syntax.

---

src/components/ClimbDropdown.vue
src/components/RouteList.vue

Remove weird vertical padding that the RouteList component
had by virtue of using <v-list>.
Also reduce elevation on ClimbDropdown's button since it
looked a bit heavy in the unclimbed state.

Remove vertical padding on RouteList.

---

src/components/StatisticsList.vue

Explicitly set the 'name' property when declaring the
StatisticsList component. Without this, recursive
invocations (used for nested statistics) aren't expanded in
production builds.

Fix recursive use of StatisticsList component in prod.

---

admin/scores.go

Omit teams without any members from the Admin Cloud
Function's scoreboard output. These break the table layout
and aren't useful to display.

Make scoreboard exclude empty teams.

---

src/firebase/index.ts
src/main.ts
src/views/Profile.vue
src/views/Routes.vue
src/views/Statistics.vue

Register handlers that report uncaught errors and rejected
promises to Stackdriver in production builds.
Also improve existing error handling. In particular, try to
handle rejected Firestore promises, since the errors that
are logged there by default seem generic and useless.

Report all errors to Stackdriver.

---

jest.config.js
package-lock.json
package.json
src/components/ClimbDropdown.test.ts
tsconfig.json

Unit tests can be run using 'npm run test:unit'. There's
currently just a single placeholder test file for
the ClimbDropdown component.
I had to upgrade to babel-core 7.0.0-bridge.0 to get around
supremely unhelpful import errors about the vue-cli polyfill
Babel plugin. I suspect that vue-cli is missing a
dependency: https://stackoverflow.com/q/56462456/

Add support for client unit testing using Jest.

---

src/firebase/index.ts
src/firebase/logger.test.ts
src/firebase/logger.ts

Update the Logger class to send accumulated log records just
once every 10 seconds by default, and to retry sending on
failure. Also add a bunch of unit tests.

Send log records to Stackdriver in batches.

---

src/firebase/logger.test.ts
src/firebase/logger.ts
tsconfig.json

Make the Logger class hold off on scheduling _sendQueued()
calls when the browser reports that the device was offline.
As soon as the device comes online, we schedule sending.
I'm also adding Node types to our TypeScript config. I'm not
completely sure that we'll need this, though, as zero lucks
were given when I tried to mock the navigator.onLine
property in tests.
Finally, I improved comments a bit and switched to Chrome's
style of putting parameter names in pipes (e.g. "Subscribed
to events of type |name|.") to make them easier to read.

Defer sending log records while offline.

---

src/firebase/index.ts
src/mixins/Perf.ts
src/views/Profile.vue
src/views/Routes.vue
src/views/Statistics.vue

Add a new 'Perf' Vue mixin that views can use to report
their initial load times to Stackdriver at DEBUG severity.
Also update views to report 'profile_loaded',
'routes_loaded', and 'stats_loaded' records.

Report performance data.

---

src/App.vue

Fix an issue where the App view sometimes wouldn't hear
about changes to the logged-in state, resulting in the
toolbar being shown at the login screen or hidden while
logged in. I suspect that I introduced this regression when
I made loggedIn be a computed property rather than a method.

Fix toolbar visibility issues.

---

src/firebase/index.ts
src/mixins/Perf.ts
src/mixins/UserLoader.ts
src/views/Profile.vue
src/views/Routes.vue
src/views/Statistics.vue

Add a new UserLoader mixin component that automatically
loads the user and team (if applicable) documents from
Firestore and watches for team changes.
This replaces duplicated (and incorrect, in some cases) code
from the Profile, Routes, and Statistics views.

Add UserLoader mixin.

---

src/App.vue
src/components/Toolbar.vue
src/firebase/auth.ts
src/firebase/firestore.ts
src/firebase/functions.ts
src/firebase/init.ts
src/log/index.ts
src/log/logger.test.ts
src/log/logger.ts
src/main.ts
src/mixins/Perf.ts
src/mixins/UserLoader.ts
src/router/index.ts
src/views/Login.vue
src/views/Profile.vue
src/views/Routes.vue
src/views/Statistics.vue

Split the monolithic firebase/index.ts file into separate
auth.ts, firestore.ts, functions.ts, and init.ts files to
make it easier for other files to import just the necessary
functionality.
Also move the logging-specific code into a new log
directory. It has minimal Firebase dependencies, so refactor
it slightly so it can be imported without pulling in
the bulky Firebase libraries.

Split firebase/index.ts into more files.

---

src/App.vue
src/firebase/index.ts
src/views/Routes.vue

I didn't notice it before, but there's an option to tell
Firestore to sync its state between tabs, which allows
persistence a.k.a. offline mode to be used when the site is
open in multiple tabs (which can happen easily after
installing the PWA). Pass this when enabling persistence.
Also make the Routes view display a warning if persistence
is disabled for some reason (ancient browser?).

Enable tab-syncing for Firestore persistence.

---

package.json
src/components/Toolbar.test.ts
src/components/Toolbar.vue
src/firebase/mock.ts
src/router/index.ts
src/router/routes.ts
src/testutil.ts
src/views/Profile.test.ts
src/views/Profile.vue

Display a confirmation dialog before signing the user out.
The "Sign out" item in the navigation drawer is easy to
accidentally click, and doing so is problematic when the
device doesn't have network connectivity. Also add a divider
between the other items and "Sign out" and write some tests.
Tangentially, switch the titles on dialogs displayed in the
Profile view to use sentence case instead of title case.
This is pretty arbitrary, but I think that "Sign Out" looks
funny and I'd like to be consistent.
Also add a "test:unit:only" script to package.json to make
it easier to run tests from a single file, e.g. "npm run
test:unit:only Toolbar".

Add confirmation dialog for "Sign out" nav item.

---

src/firebase/mock.ts
src/log/index.ts
src/log/logger.test.ts

Rewrite a bunch of calls like
"new Promise(resolve => { resolve('foo') })" to instead use
the shorter and clearer "Promise.resolve('foo')" for
returning an already-resolved promise with a given value.
Ditto with Promise.reject.
Also improve console logging output a bit.

Use Promise.resolve and Promise.reject.

---

go/admin/admin.go
go/admin/clear_scores.go
go/admin/empty_teams.go
go/admin/firestore.go

Update the page served by the Admin Cloud Function to
support clearing all scores and deleting teams that don't
have any members.
No unit tests, since Firestore provides zero test support
and no way to run locally, and writing a mock implementation
seems like it would be a lot of work without much benefit.

Update Admin page to clear scores and delete empty teams.

---

.gitignore
.travis.yml
firestore.test.ts
jest.config.js
package-lock.json
package.json

These tests make use of the Cloud Firestore emulator, which
can be set up by running "firebase
setup:emulators:firestore" (but which also requires
installing Java, e.g. via the openjdk-8-jre package).
Update package.json config so the new tests can be run using
"npm run test:firestore", and also update the Travis config
to execute them.

Add tests for Cloud Firestore security rules.

---

firestore.rules
firestore.test.ts
src/firebase/index.ts

Update firestore.rules to validate documents written by
users, and add additional unit tests that verify the rules.
The rules perform fairly-extensive consistency checks
between user, team, and invite docs.
The updated rules are complicated, but there are also a lot
of tests now. I manually verified that the general flows of
signing in for the first time and creating, leaving, and
joining a team seems to still work after pushing these rules
to the dev instance.
Also update firestore.test.ts to not bother applying rules,
since they already appear to be loaded automatically by the
emulator.

Add validation to Cloud Firestore security rules.

---

src/firebase/mock.ts
src/views/Login.test.ts
src/views/Login.vue

Email signin was broken by a recent Firestore validation
change that required that user docs contain names -- no
display name is supplied when signing in via email, so we
now fall back to 'Unknown Climber' in that case.

Use fallback display name for email login.

---

.env.example
.gitignore

Rename the existing placeholder .env file to .env.example,
and make .env get ignored by git. We should switch to using
.env for per-site configuration since .env.local isn't
loaded in all cases (e.g. Nightwatch seems to only look at
.env), and the dotenv package doesn't allow overriding
existing values by manually loading .env.local.

Rename .env to .env.example.

---

INSTALL.md
deploy_cloud_function.sh

Add a script that deploys a Cloud Function to the current
GCP project. The gcloud command for doing this is long, and
it's easy to mess up and accidentally deploy to the wrong
project.
Also make minor updates to INSTALL.md.

Add deploy_cloud_function.sh.

---

src/firebase/mock.ts
src/views/Login.vue

- Remove the card around the FirebaseUI auth element, since
the email auth widget is itself rendered in a card on
large displays.
- Give the view a white background so the email auth widget
looks okay on mobile.
- Disable the account chooser (only used for email auth)
since it's ugly and doesn't seem to work right.
- Display the spinner while we're creating the user doc
after email auth, since there's no redirect and the UI
hence isn't already hidden by the existing logic for
OAuth.

Visual improvements to login view.

---

src/firebase/mock.ts
src/views/Profile.test.ts
src/views/Profile.vue
src/views/Routes.test.ts
src/views/Routes.vue

When creating a team, try to find an unused invite code up
to ten times before failing. Before, we'd just try to insert
a document for the new code without checking it first. The
Firestore security rules should reject collisions, but it
seems nicer to handle them gracefully by retrying.
If my math is right, the previously probability of a
collision with 100 existing teams was just 0.0001, but why
not reduce that to 1e-40?
Also fix some broken interpolated error messages.

Make Profile view search for unused invite codes.

---

firebase.json

Run the Firestore emulator used by "npm run test:firestore"
on a different port. By default it uses port 8080, which
conflicts with "npm run serve".

Run Firestore emulator on port 8085.

---

.env.example
.gitignore
e2e/globals.ts
e2e/tests/test.ts
nightwatch.conf.js
package-lock.json
package.json

Use Nightwatch to perform end-to-end testing via a new "npm
run test:e2e" command. The test currently goes through
first-time login and exercises all of the functionality
exposed by the profile view. Nightwatch doesn't know
anything about TypeScript, so the npm command runs tsc to
transpile the code to JS first.
I haven't figured out how to make any of this work with
Travis yet, and it currently requires that the site is being
served at localhost:8080 (e.g. via "npm run serve").

Add end-to-end tests using Nightwatch.

---

e2e/tests/test.ts
src/log/index.ts
src/log/logger.test.ts
src/log/logger.ts
src/views/Login.vue
src/views/Profile.vue

- Remove extra quoting around E2E test console messages.
- Write log messages to the console immediately instead of
batching them.
- Fix a subtle bug where Logger could claim its own queued
logs, which would result in them not getting sent when
they should.
- Fix an issue in the Login view where 'login_loaded' was
never logged, due to the 'ready' variable initially
starting out true. Renamed the variable to 'showUI', which
is more accurate.
- Make the Profile view's 'leave_team' message include the
team ID.

Make miscellaneous improvements to logging.

---

README.md
go/admin/routes_test.go
go/db/firestore.go
src/models.ts
src/views/Routes.test.ts
src/views/Routes.vue

Update the Admin Cloud Function to include area IDs when
writing the global/sortedData Firestore doc. I'd initially
left this out since we don't need it when displaying routes,
but it'd actually be useful to use as a v-for key and during
end-to-end testing.

Include area IDs in global/sortedData.

---

.env.example
README.md
e2e/globals.ts
e2e/pages/profile.ts
e2e/tests/test.ts
firestore.rules
firestore.test.ts
src/models.ts
src/views/Profile.test.ts
src/views/Profile.vue
src/views/Routes.vue
src/views/Statistics.vue

Remove old logic that transferred a user's climbs from the
team doc to their user doc when they left their team.
Instead, if a user leaves a team after reporting climbs,
preserve their entry in the team's 'users' map. We let the
user re-join the team later but no one else can take their
place.
Also update end-to-end tests to use two separate users.

Prevent replacing team member after they report climbs.

---

e2e/tests/test.ts

Put "E2E" in the names of teams and users created by the
end-to-end test to make it easier to recognize them when
browsing through Cloud Firestore data.

Give E2E users and teams more descriptive names.

---

e2e/pages/login.ts
src/views/Routes.test.ts
src/views/Routes.vue

After the move to Vuetify 2, expanding areas in the Routes
view became super-janky on a Pixel 2 phone running Chrome
77. Setting the 'accordion' attribute on v-expansion-panels
and 'eager' on v-expansion-panel-content seems to improve
this.
Unrelatedly, increase the login timeout in end-to-end tests
from 5 seconds to 15 seconds, since login depends on an
external service and since I just saw it time out.

Improve performance when expanding areas in Routes view.

---

README.md
src/components/GradeSlider.test.ts
src/components/GradeSlider.vue
src/models.ts
src/router/routes.ts
src/views/Routes.test.ts
src/views/Routes.vue
src/views/RoutesNav.vue

Add support for filtering which routes are displayed in the
Routes view, currently just via a minimum and maximum grade.
A new GradeSlider component is introduced and used in a
dialog in the Routes view. A new RoutesNav component is also
used to place a "Filters" button in the toolbar for opening
the dialog.
Filters are saved to the user doc in Cloud Firestore, but
they aren't reflected in the route listing yet.

Support setting grade-based route filters.

---

e2e/pages/profile.ts

Send keystrokes individually and pause 5 ms between each
when interacting with the Profile view during end-to-end
testing. This is a speculative fix for scrambled input
that's shown up a few times in Travis, e.g.
https://travis-ci.org/derat/ascenso/jobs/587196209.

Try to avoid scrambled text input in end-to-end tests.

---

src/components/GradeSlider.test.ts
src/components/GradeSlider.vue
src/components/RouteList.test.ts
src/components/RouteList.vue
src/models.ts
src/views/Routes.test.ts
src/views/Routes.vue

Update the RouteList component to accept minGrade and
maxGrade parameters. If a range is supplied, routes with
grades outside of it are displayed with reduced opacity.
Update the Routes view to pass the range selected via the
filters dialog.

Make RouteList visually deemphasize filtered-out routes.

---

e2e/pages/profile.ts

Wait longer for dialogs to be dismissed after clicking
buttons on the profile page. The failure at
https://travis-ci.org/derat/ascenso/jobs/600449304 looks
like it was probably caused by Firestore slowness.

Make E2E test wait up to 10 seconds on profile page.

---

.travis.yml

Set the CHROMEDRIVER_VERSION environment variable to
"LATEST" in .travis.yml to instruct the chromedriver Node
package to install the current stable version of
Chromedriver (which is used to control Chrome in end-to-end
testing). See https://www.npmjs.com/package/chromedriver for
more details.
The package's default version of Chromedriver appears to lag
behind Chrome's stable channel:
https://travis-ci.org/derat/ascenso/jobs/601486566 failed
because Chrome 78.0.3904.70 was paired with a version of
Chromedriver that expects Chrome 76.

Make Travis install latest stable Chromedriver release.

---

e2e/pages/profile.ts

Increase the timeout in end-to-end tests for joining or
leaving a team from 10 seconds to 20 seconds. I'm still
seeing occasional failures in the automated Travis runs,
e.g. https://travis-ci.org/derat/ascenso/builds/614736317.
I haven't been able to reproduce the failures locally, but I
assume that Firebase updates are being slow (network
issues?).

Increase E2E timeout for joining/leaving team to 20 seconds.

---

package-lock.json

Update the handlebars package from 4.5.1 to 4.5.3 to address
several vulnerabilities identified by "npm audit". (Why does
a templating library have so many vulnerabilities?)

Update handlebars to 4.5.3.

---

jest.config.js
src/locale/en.ts
src/locale/es.ts
src/main.ts
src/plugins/i18n.ts
src/plugins/vuetify.ts
src/testutil.ts
src/views/Profile.test.ts
src/views/Profile.vue

Configure Vuetify to use vue-i18n for its own translations.
https://vuetifyjs.com/en/customization/internationalization
has more information.
Also restructure our vue-i18n code so that each language has
its own file under src/locale and so that each component's
translations are grouped together, and simplify vue-i18n
setup for tests.
I'd initially thought we could drop vue-i18n and switch to
just using Vuetify's built-in i18n support, but it seems
like it's less featureful than vue-i18n (e.g. no
pluralization support).

Instruct Vuetify to use vue-i18n.

---

src/views/Profile.vue

Change Error constructor calls using vue-i18n's this.$t() to
instead use this.$t().toString(). Otherwise, we get more
stupid "Type 'LocaleMessages' is not assignable to type
'string'" errors from TypeScript. (Oddly, E2E tests were
still passing.)

Add missing string casts to Profile view.

---

e2e/pages/profile.ts
src/views/Profile.vue

Update E2E tests to use different logic after dismissing
dialogs to avoid an apparent race where Nightwatch's
waitForElementNotVisible() method fails if Vue has already
removed the selected element from the DOM. Also increase
createTeam()'s timeout to 20 seconds to match other methods.
Additionally, remove an incorrect early return in
checkUserOnTeam() that resulted in the team roster not
actually being checked, and fix the check to look at the
full roster instead of just seeing the first member. (Why
didn't TypeScript issue an unreachable code error about the
early return?)

Try to fix profile dialog dismissal race in E2E tests.

---

e2e/pages/login.ts

I just saw another end-to-end test failure while waiting for
the login page's email field to appear, so increase the
timeout from its default 5 seconds to 20 seconds. Also
increase a few related timeouts from 15 seconds to 20
seconds.

Increase E2E timeout when waiting for login email field.

---

package-lock.json

Upgrade terser-webpack-plugin from 1.3.0 to 1.4.3 to resolve
serialize-javascript vulnerabilities identified by "npm
audit". For whatever reason, npm also decided to convert a
bunch of packages to be non-dev dependencies. *shrug*
It looks like we still include the affected version of
serialize-javascript due to @vue/cli-service, but updating
that package broke everything the last time I tried to do it
so I'm going to save it for a separate change.

Upgrade terser-webpack-plugin to resolve vulnerabilities.

---

package-lock.json
package.json

Upgrade @vue/cli-service and a zillion related vue-cli
packages to remove a dependency on a vulnerable version of
serialize-javascript identified by "npm audit".
Also manually install vuetify-loader@1.4.3 to fix this error
from "npm run serve" after upgrading vue-cli:
ERROR  Error: [VuetifyLoaderPlugin Error] No matching rule
for vue-loader found.
Make sure there is at least one root-level rule that uses
vue-loader.

Upgrade to @vue/cli-service@4.1.2 to fix vulnerabilities.

---

package-lock.json
package.json

Update the vuetify package from version 2.1.9 to 2.2.4. Per
the release notes, there are no additional steps needed for
going to 2.2.

Upgrade to Vuetify to v2.2.4.

---

.browserslistrc
.eslintrc.js
package-lock.json
package.json
postcss.config.js
src/firebase/mock.ts
src/log/index.ts
src/log/logger.test.ts
src/log/logger.ts
src/testutil.ts
src/views/Profile.vue
src/views/Statistics.vue

Manually install @vue/eslint-config-typescript@latest and
upgrade to @typescript-eslint/eslint-plugin@^2.7.0
@typescript-eslint/parser@^2.7.0. This appears to finally
eliminate all of the warnings about unsatisfied peer
dependencies that I'd see when running commands like 'npm
prune'.

Upgrade TypeScript ESLint packages.

---

src/components/ClimbDropdown.vue
src/components/LocalePicker.vue
src/components/Toolbar.vue
src/views/Profile.vue
src/views/Routes.vue
src/views/RoutesNav.vue
src/views/Statistics.vue

Use the 'v-t' attribute in elements that just contain
straightforward translated text instead of calling the $t
function via '{{ $t(...) }}'. 'v-t' is allegedly faster:
https://kazupon.github.io/vue-i18n/guide/directive.html#t-vs-v-t

Use 'v-t' attribute for simple translations.

---

public/index.html
src/views/Routes.vue

Update the Routes view to display a sync icon and the number
of pending updates in the bottom-right corner of the
viewport when there are climb state changes that haven't
been synced with the backend yet.
Also change the way that we import Material icons in
index.html, since the old non-Roboto import doesn't appear
to contain the 'sync' icon. The existing icons in the
Toolbar view's navigation drawer are still rendered
correctly.

Display sync icon in Routes view for pending writes.

---

package-lock.json
package.json
src/components/LocalePicker.vue
src/locale/es-PR.ts
src/main.ts
src/plugins/i18n.ts
src/views/Login.vue

Add a dependency on the tiny-cookie package and use it to
save and restore the user's locale choice.
Unrelatedly, change a 'Tu Nombre' string to 'Tu nombre' to
match the capitalization used elsewhere in the UI.

Save the user's locale selection in a cookie.

---

src/firebase/mock.ts

Add a do-nothing mock (actually, stub?) implementation of
the waitForPendingWrites method. Commit 1494565473 made the
Routes view call this, so exceptions started getting thrown
by unit tests. The tests still pass so I didn't notice it.

Add waitForPendingWrites to mock Firestore implementation.

---

src/views/Routes.vue

I think that the root view was retaining a reference to the
Routes view when we navigated away from it, by virtue of
Routes not removing its listener for 'show-route-filters'
events. Fix this.

Fix Routes view memory leak.

---

public/index.html
src/components/Toolbar.vue
src/locale/en-US.ts
src/locale/es-PR.ts
vue.config.js

Add data attributes to the <html> element at build time that
are later used by the Toolbar component to display the build
timestamp and git commit at the bottom of the navigation
drawer. I think that this will be useful in debugging PWA
caching issues.

Display build info in nav drawer.

---

src/locale/en-US.ts
src/locale/es-PR.ts
src/views/Profile.vue

Make various strings in the Profile view shorter so they'll
fit onscreen on iPhone 5/SE, which has a screen width of
just 320 display units. This is particularly a problem in
Spanish.
Also conditionally set the 'small' attribute on the main
buttons in the Profile view for screens with widths up to
400 display units.
Finally, fix an incorrect string in the "Join team" dialog.
It looks like I used the wrong ID here when I finished
translating the Profile view in 3990730e.

Shorten long UI strings to fit on small screens.

---

package-lock.json
package.json

Unit tests started failing in Travis (despite the fact that
this repo hasn't been modified in more than a month) with
errors like the following from
https://travis-ci.org/github/derat/ascenso/builds/692361530:
[BABEL] /home/travis/build/derat/ascenso/src/views/Profile.test.ts:
No "exports" main resolved in /home/travis/build/derat/ascenso/node_modules/@babel/helper-compilation-targets/package.json
(While processing: "/home/travis/build/derat/ascenso/node_modules/@vue/cli-plugin-babel/preset.js")
Some searching points toward
https://github.com/babel/babel/issues/11216, alleging that
this is caused by a regression (or maybe just a change in
undocumented behavior) in Node 13.9. Babel 7.8.7 and later
apparently contains a workaround.
The Travis logs claim that Node 12.17.0 is still being …

Upgrade Babel to 7.10.1 from 7.0.0.

---

ascenso.go
deploy_cloud_function.sh
go.mod
go/admin/admin.go
go/admin/clear_scores.go
go/admin/empty_teams.go
go/admin/routes.go
go/admin/routes_test.go
go/admin/scores.go
go/admin/scores_test.go
go/log/log.go
go/test/func.go

Google is deprecating the go111 runtime on 2020-08-05 and
blocking deployments starting 2021-02-15 (since Go 1.11 is
now unspported), so switch to go113.
To make this work, I had to update go.mod and local imports
to use the proper fully-qualified module name (ascenso ->
github.com/derat/ascenso), and I also needed to update
deploy_cloud_function.sh to manually set the GCP_PROJECT
environment variable since it's no longer automatically set
by the runtime.
https://cloud.google.com/functions/docs/concepts/go-runtime
neglects mentioning this, but the change is shown at
https://cloud.google.com/functions/docs/env-var.

Use go113 runtime for Cloud Functions.

---

src/views/Login.test.ts
src/views/Login.vue

Update the Login view to keep the logo and FirebaseUI auth
container onscreen while finalizing login and waiting for
redirect, and display the spinner in a v-overlay (which
automatically centers it and blocks input).
I wasted a bunch of time trying to figure out why Google
login wasn't working in an incognito window. Apparently
third-party cookies are required, but FirebaseUI seems to
only report this via an ugly div in the auth container
rather than throwing an error or running the signInFailure
callback.

Keep UI onscreen while finishing login.

---

go/admin/scores.go
go/admin/scores_test.go

Add title attributes to the Admin Cloud Function's
scoreboards that list each user's climbs. This is helpful
when comparing the submitted scores against paper scorecards
at the end of the competition.

Add tooltips listing climbs to scoreboards.

---

go/admin/admin.go
go/admin/clear_scores.go
src/firebase/mock.ts
src/mixins/UserLoader.ts
src/views/Statistics.vue

Add a checkbox that can be used to also delete all teams
while clearing scores.
Also update the Statistics view to avoid showing the image
tab if the user isn't on a team.

Support deleting teams from Admin Cloud Function.

---

src/components/ClimbDropdown.vue
src/components/Toolbar.vue
src/views/Profile.vue
src/views/Routes.vue
src/views/RoutesNav.vue
src/views/Statistics.vue

The v-t attribute, vue-i18n's version of v-text, apparently
replaces the contents of the element that it's used on, so
it shouldn't be set on components. Otherwise, we get errors
like the following when the 'Leave team' dialog is closed:
Uncaught DOMException: Failed to execute 'removeChild' on
'Node': The node to be removed is not a child of this
node.
I'm still keeping a few uses of v-t in the ClimbDropdown
component, since it's allegedly more performant than $t()
and I haven't noticed any problems there.

Remove (almost) all uses of the v-t attribute.

---

src/views/Profile.test.ts
src/views/Profile.vue

Remove leading, trailing, and repeated whitespace when
creating a new team, as is already done when changing the
user or team name.

Update Profile view to clean name when creating team.

---

nightwatch.conf.js
package-lock.json
package.json
src/App.vue
src/components/Card.vue
src/views/Profile.vue
src/views/Statistics.vue

Run 'npm install vuetify@latest' to install vuetify@2.6.4.
That resulted in "SassError: @use is coming soon, but it's
not supported in this version of Dart Sass." when running
'npm run serve', so I also ran 'npm install sass@latest' to
upgrade to sass@1.49.9 (from 1.22.12).
That resulted in a zillion deprecation warnings about
Vuetify using deprecated things in Sass, so then I ran 'npm
install sass@1.25.0' to downgrade to the version that
allegedly introduced @use, which seems to work.
I also had to make some minor tweaks in response to padding
and margin changes in Vuetify.

Upgrade to Vuetify 2.6.4 (from 2.2.18).
